name: uncle_toms_hris
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  geolocator: ^10.1.0

  cupertino_icons: ^1.0.8
  http: ^0.13.6
  shared_preferences: ^2.2.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true